#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."
script/set-version "$1"
cp crates/generate/src/dsl.d.ts lib/binding_web/dsl.d.ts
cp crates/generate/src/dsl.d.ts lib/binding_web/dsl.d.cts
cd lib/binding_web
npm ci
npm run build
npm run build:debug
CJS=true npm run build
CJS=true npm run build:debug
npm run build:dts
